// <auto-generated />
namespace banhoa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddHoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddHoa));
        
        string IMigrationMetadata.Id
        {
            get { return "202006120636599_AddHoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
